name: my-web-ci-cd

on: [push, pull_request]

jobs:
    all:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                threads:
                    - '4'
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install Depedencies
              run: make install

            - name: Run Code Generation
              run: make generate

            - name: Run Linter
              run: make lint

            - name: Run Typecheck
              run: make typecheck

            - name: Run Format Check
              run: make format-check

            - name: Run Tests
              env:
                  ORIGIN: http://localhost:3000
                  EMAIL: ${{ secrets.EMAIL }}
                  PASS: ${{ secrets.PASS }}
              run: |
                  make test
                  rm -rf __tests__

            - name: Run Build
              run: make build
